// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHmRYZ8AqcNyyvv5x0PiseQM49WgrvJg',
    appId: '1:1022787331678:web:b2d2c5a4827b47fb96b6cf',
    messagingSenderId: '1022787331678',
    projectId: 'oshimai-app',
    authDomain: 'oshimai-app.firebaseapp.com',
    storageBucket: 'oshimai-app.appspot.com',
    measurementId: 'G-6GQTTNYXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJStUEHgnFqPSV7te97WxGX-y0AEolDIs',
    appId: '1:1022787331678:android:310861d0bcad4c2a96b6cf',
    messagingSenderId: '1022787331678',
    projectId: 'oshimai-app',
    storageBucket: 'oshimai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwIHsZvB8WE_2b-VQPmEZaUEA5kHhvrg8',
    appId: '1:1022787331678:ios:8acf917a2fb8512696b6cf',
    messagingSenderId: '1022787331678',
    projectId: 'oshimai-app',
    storageBucket: 'oshimai-app.appspot.com',
    iosClientId: '1022787331678-t0f1sl9vnhbp3ardfn95dvlv4k8hiagm.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshimai',
  );
}
